---

- name: Ensure group "{{ minecraft_group }}" exists
  group:
    name: "{{ minecraft_group }}"
    state: present

- name: create main user
  user:
    name: "{{ main_user }}"
    group: "{{ minecraft_group }}"
    shell: /bin/bash
    system: true
    create_home: yes
    home: /opt/minecraft

- name: create minecraft server directory
  file:
    path: "{{ server_path }}"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ minecraft_group }}"
