---

- name: Install Required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages | default([]) }}"

- name: Update apt cache
  apt:
    update_cache: yes

- name: install {{ openjdk_release }}
  apt:
    name: "{{ openjdk_release }}"
